### ISSUE TITLE
Add methods .mapParallel and .findParallel

### ISSUE THREAD

**Issue by AnnaHalk** [dm-kamaev/promise_mtd#1]
Hello!
Is it possible to add in the library methods for concurrent execution for `map` and `find`  namely `mapParallel` and `.findParallel` ?
I guess it will be something like that:
```js
const list = await promiseMtd.mapParallel(array,  { pool: 3 }, cb);

const found = await promiseMtd.findParallel(array,  { pool: 3 }, cb);
```

**Comment by dm-kamaev** [comment]
I added this methods in the version [v3.0.0](https://github.com/dm-kamaev/promise_mtd/releases/tag/v3.0.0).
